name: Update NordVPN readme files

on:
  schedule:
    - cron: 0 3 * * *

jobs:
  update_cities:
    name: Update NordVPN cities list
    runs-on: ubuntu-latest
    env:
      FILE: "CITIES.md"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Update ${{ env.FILE }}
        id: createfile
        shell: bash
        run: |
          {
            echo "# List of locations with NordVPN servers"
            echo ""
            echo "Country | Code | ID | City | ID"
            echo "--- | --- | --- | --- | ---"
            curl -s https://api.nordvpn.com/v1/servers/countries | jq -r '.[] | . as $parent | .cities[] | [$parent.name, $parent.code, $parent.id, .name, .id] | "\(.[0]) | \(.[1]) | \(.[2]) | \(.[3]) | \(.[4])"'
          } > ${{ env.FILE }}

          DATE=$(date +%y%m%d)

          echo "cities_date=${DATE}" >> $GITHUB_ENV

          echo "Base date=${DATE}"

      - name: Create Pull Request, update ${{ env.FILE }}, date ${{ env.cities_date }}
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          branch: mdupdaterbot/update-${{ env.FILE }}
          branch-suffix: short-commit-hash
          commit-message: Update ${{ env.FILE }}, date ${{ env.cities_date }}
          delete-branch: true
          title: Update ${{ env.FILE }}, date ${{ env.cities_date }}
          body: |
            Update ${{ env.FILE }}, date ${{ env.cities_date }}

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions

  update_countries:
    name: Update NordVPN countries list
    runs-on: ubuntu-latest
    env:
      FILE: "COUNTRIES.md"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Update ${{ env.FILE }}
        id: createfile
        shell: bash
        run: |
          {
            echo "# List of countries with NordVPN servers"
            echo ""
            echo "Country | Code | ID"
            echo "--- | --- | ---"
            curl -s https://api.nordvpn.com/v1/servers/countries | jq -r '.[] | [.name, .code, .id] | "\(.[0]) | \(.[1]) | \(.[2])"'
          } > ${{ env.FILE }}

          DATE=$(date +%y%m%d)

          echo "countries_date=${DATE}" >> $GITHUB_ENV

          echo "Base date=${DATE}"

      - name: Create Pull Request, update ${{ env.FILE }}, date ${{ env.countries_date }}
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          branch: mdupdaterbot/update-${{ env.FILE }}
          branch-suffix: short-commit-hash
          commit-message: Update ${{ env.FILE }}, date ${{ env.countries_date }}
          delete-branch: true
          title: Update ${{ env.FILE }}, date ${{ env.countries_date }}
          body: |
            Update ${{ env.FILE }}, date ${{ env.countries_date }}

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions

  update_groups:
    name: Update NordVPN VPN server groups
    runs-on: ubuntu-latest
    env:
      FILE: "GROUPS.md"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Update ${{ env.FILE }}
        id: createfile
        shell: bash
        run: |
          {
            echo "# List of server groups"
            echo ""
            echo "Name | Identifier | ID"
            echo "--- | --- | ---"
            curl -s https://api.nordvpn.com/v1/servers/groups | jq -r '.[] | [.title, .identifier, .id] | "\(.[0]) | \(.[1]) | \(.[2])"'
          } > ${{ env.FILE }}

          DATE=$(date +%y%m%d)

          echo "groups_date=${DATE}" >> $GITHUB_ENV

          echo "Base date=${DATE}"

      - name: Create Pull Request, update ${{ env.FILE }}, date ${{ env.groups_date }}
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          branch: mdupdaterbot/update-${{ env.FILE }}
          branch-suffix: short-commit-hash
          commit-message: Update ${{ env.FILE }}, date ${{ env.groups_date }}
          delete-branch: true
          title: Update ${{ env.FILE }}, date ${{ env.groups_date }}
          body: |
            Update ${{ env.FILE }}, date ${{ env.groups_date }}

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions

  update_technologies:
    name: Update NordVPN VPN technologies
    runs-on: ubuntu-latest
    env:
      FILE: "TECHNOLOGIES.md"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Update ${{ env.FILE }}
        id: createfile
        shell: bash
        run: |
          {
            echo "# List of technologies"
            echo ""
            echo "Name | Identifier | ID"
            echo "--- | --- | ---"
            curl -s https://api.nordvpn.com/v1/technologies | jq -r '.[] | [.name, .identifier, .id] | "\(.[0]) | \(.[1]) | \(.[2])"'
          } > ${{ env.FILE }}

          DATE=$(date +%y%m%d)

          echo "technologies_date=${DATE}" >> $GITHUB_ENV

          echo "Base date=${DATE}"

      - name: Create Pull Request, update ${{ env.FILE }}, date ${{ env.technologies_date }}
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          branch: mdupdaterbot/update-${{ env.FILE }}
          branch-suffix: short-commit-hash
          commit-message: Update ${{ env.FILE }}, date ${{ env.technologies_date }}
          delete-branch: true
          title: Update ${{ env.FILE }}, date ${{ env.technologies_date }}
          body: |
            Update ${{ env.FILE }}, date ${{ env.technologies_date }}

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions
